meta_product_name: "Planternative"
meta_title: "Planternative - find plant-based alternatives for your favourite meals"
meta_description: "Keep calm, plants do have protein. Find plant-based alternatives for your favourite meals."
meta_image: "https://images.unsplash.com/photo-1536147116438-62679a5e01f2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"
