meta_product_name: "Planternative"
meta_title: "Planternative - find plant-based alternatives for your favourite meals"
meta_description: "Keep calm, plants do have protein. Find plant-based alternatives for your favourite meals."
meta_image: "http://res.cloudinary.com/dqtmlpkmm/image/upload/default_avatar_yubqpb"
